services:
  
  db:
    image: postgres:15-alpine
    container_name: hoopp-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hoopp_intelligence
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hoopp-net

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: hoopp-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"    
    depends_on:
      - db
    networks:
      - hoopp-net
  ingestor:
    build: ./ingestor
    container_name: hoopp-ingestor

    depends_on:
     - db
    volumes:
     - ./ingestor/src:/app/src
    networks:
      - hoopp-net
  
  api:
    build: ./api
    container_name: fastapi
    ports: 
     - 8000:8000
    depends_on:
     - db 
    networks:
     - hoopp-net 
    volumes:
     - ./api:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  hoopp-net:
    driver: bridge

volumes:
  postgres_data:   